import Head from 'next/head'
import { FC } from 'react'

interface HeadLayoutProps {
	title?: string
}

export const HeadLayout: FC<HeadLayoutProps> = ({ title }) => {
	return (
		<Head>
			<title>{title}</title>
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
	)
}

HeadLayout.defaultProps = {
	title: 'SpendSmartly',
}
